export default {
    "login": "Chellii",
    "id": 56842722,
    "node_id": "MDQ6VXNlcjU2ODQyNzIy",
    "avatar_url": "https://avatars.githubusercontent.com/u/56842722?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Chellii",
    "html_url": "https://github.com/Chellii",
    "followers_url": "https://api.github.com/users/Chellii/followers",
    "following_url": "https://api.github.com/users/Chellii/following{/other_user}",
    "gists_url": "https://api.github.com/users/Chellii/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Chellii/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Chellii/subscriptions",
    "organizations_url": "https://api.github.com/users/Chellii/orgs",
    "repos_url": "https://api.github.com/users/Chellii/repos",
    "events_url": "https://api.github.com/users/Chellii/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Chellii/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Chaimae El Oiriagli",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "twitter_username": null,
    "public_repos": 22,
    "public_gists": 0,
    "followers": 19,
    "following": 15,
    "created_at": "2019-10-21T17:54:06Z",
    "updated_at": "2022-07-17T11:09:16Z"
  }